# CONSOLIDATED DOCKER COMPOSE CONFIGURATION
# Google Maps Data Scraper - LeadTap Platform
# 
# This file consolidates all Docker configurations for different deployment scenarios:
# - Development (with hot reload)
# - Simple Production (minimal services)
# - Full Production (with monitoring, caching, etc.)
# - Backend-only deployment

# =============================================================================
# ENVIRONMENT CONFIGURATION
# =============================================================================
# Set DEPLOYMENT_TYPE environment variable to choose configuration:
# - development: Full stack with hot reload and development features
# - simple: Minimal production setup (backend + frontend + SQLite)
# - production: Full production with PostgreSQL, Redis, monitoring
# - backend-only: Backend API only

# =============================================================================
# SHARED NETWORK
# =============================================================================
networks:
  leadtap-network:
    driver: bridge

# =============================================================================
# SHARED VOLUMES
# =============================================================================
volumes:
  # Database volumes
  postgres_data:
  mysql_data:
  sqlite_data:
  
  # Cache volumes
  redis_data:
  
  # Monitoring volumes
  prometheus_data:
  grafana_data:
  
  # Application volumes
  backend_static:
  frontend_static:
  uploads_data:

# =============================================================================
# SERVICES
# =============================================================================
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: leadtap-backend
    ports:
      - "8000:8000"
    environment:
      # Core configuration
      - ENVIRONMENT=${ENVIRONMENT:-development}
      - DEBUG=${DEBUG:-true}
      - SECRET_KEY=${SECRET_KEY:-dev-secret-key-change-in-production}
      - JWT_SECRET=${JWT_SECRET:-dev-jwt-secret-change-in-production}
      
      # Database configuration (choose one based on deployment type)
      - DATABASE_URL=${DATABASE_URL:-sqlite:///./leadtap.db}
      - POSTGRES_DB=${POSTGRES_DB:-leadtap}
      - POSTGRES_USER=${POSTGRES_USER:-leadtap}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-leadtap}
      - POSTGRES_HOST=${POSTGRES_HOST:-db}
      - POSTGRES_PORT=${POSTGRES_PORT:-5432}
      
      # Frontend configuration
      - FRONTEND_URL=${FRONTEND_URL:-http://localhost:3000}
      
      # External services
      - REDIS_URL=${REDIS_URL:-redis://redis:6379}
      - SENTRY_DSN=${SENTRY_DSN:-}
      
      # Feature flags
      - ENABLE_SSO=${ENABLE_SSO:-false}
      - ENABLE_MONITORING=${ENABLE_MONITORING:-false}
      - ENABLE_CACHING=${ENABLE_CACHING:-false}
      
    volumes:
      - ./backend:/app
      - /app/__pycache__
      - /app/venv
      - sqlite_data:/app/data
      - uploads_data:/app/uploads
    depends_on:
      - sqlite-db
    restart: unless-stopped
    networks:
      - leadtap-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s

# =============================================================================
# FRONTEND SERVICE (conditional)
# =============================================================================
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: leadtap-frontend
    ports:
      - "3000:80"
      - "443:443"
    environment:
      - VITE_API_URL=${VITE_API_URL:-http://localhost:8000}
      - VITE_ENVIRONMENT=${VITE_ENVIRONMENT:-development}
      - VITE_APP_NAME=${VITE_APP_NAME:-LeadTap}
      - VITE_APP_VERSION=${VITE_APP_VERSION:-1.0.0}
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - leadtap-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:80/"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s
    profiles:
      - development
      - simple
      - production

# =============================================================================
# DATABASE SERVICES
# =============================================================================

  # SQLite Database (for development and simple production)
  sqlite-db:
    image: alpine:latest
    container_name: leadtap-sqlite
    command: sh -c "echo 'SQLite database will be created in backend container' && tail -f /dev/null"
    volumes:
      - sqlite_data:/data
    networks:
      - leadtap-network
    # Available by default for all profiles

  # PostgreSQL Database (for full production)
  postgres-db:
    image: postgres:15-alpine
    container_name: leadtap-postgres
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-leadtap}
      - POSTGRES_USER=${POSTGRES_USER:-leadtap}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-leadtap}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - leadtap-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-leadtap} -d ${POSTGRES_DB:-leadtap}"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s
    profiles:
      - production

  # MySQL Database (alternative for production)
  mysql-db:
    image: mysql:8.0
    container_name: leadtap-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-root}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-leadtap}
      - MYSQL_USER=${MYSQL_USER:-leadtap}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-leadtap}
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
    networks:
      - leadtap-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s
    profiles:
      - production

# =============================================================================
# CACHE SERVICE (Redis)
# =============================================================================
  redis:
    image: redis:7-alpine
    container_name: leadtap-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - leadtap-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s
    profiles:
      - production

# =============================================================================
# REVERSE PROXY (Nginx)
# =============================================================================
  nginx:
    image: nginx:alpine
    container_name: leadtap-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl
      - ./nginx/sites-enabled:/etc/nginx/sites-enabled
    depends_on:
      - backend
      - frontend
    restart: unless-stopped
    networks:
      - leadtap-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:80/"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s
    profiles:
      - production

# =============================================================================
# MONITORING SERVICES (Production only)
# =============================================================================

  # Prometheus for metrics collection
  prometheus:
    image: prom/prometheus:latest
    container_name: leadtap-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    restart: unless-stopped
    networks:
      - leadtap-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:9090/-/healthy"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s
    profiles:
      - production

  # Grafana for dashboards
  grafana:
    image: grafana/grafana:latest
    container_name: leadtap-grafana
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD:-admin}
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - grafana_data:/var/lib/grafana
      - ./monitoring/grafana/dashboards:/etc/grafana/provisioning/dashboards
      - ./monitoring/grafana/datasources:/etc/grafana/provisioning/datasources
    restart: unless-stopped
    networks:
      - leadtap-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s
    profiles:
      - production

# =============================================================================
# DEPLOYMENT PROFILES
# =============================================================================
# 
# Usage:
# 
# Development (with hot reload):
#   docker-compose --profile development up
# 
# Simple Production (minimal services):
#   docker-compose --profile simple up
# 
# Full Production (with monitoring):
#   docker-compose --profile production up
# 
# Backend only:
#   docker-compose up backend sqlite-db
# 
# ============================================================================= 