from fastapi import APIRouter, Depends, HTTPException, Body
from sqlalchemy.orm import Session
from typing import Optional, List
from pydantic import BaseModel
from models import ReferralCode, User
from database import get_db
from auth import get_current_user
from datetime import datetime
import random, string

router = APIRouter(prefix="/api/referral", tags=["referral"])

class ReferralCreate(BaseModel):
    pass  # No input needed, just generate for current user

class ReferralOut(BaseModel):
    code: str
    rewards: Optional[dict]
    used_by: Optional[int]
    used_at: Optional[datetime]
    created_at: datetime

class ApplyReferralRequest(BaseModel):
    code: str

class ApplyReferralResponse(BaseModel):
    success: bool
    message: str
    rewards: Optional[dict]

@router.post("/generate", response_model=ReferralOut, summary="Generate referral code", description="Generate a unique referral code for the current user.")
def generate_referral_code(db: Session = Depends(get_db), user: User = Depends(get_current_user)):
    """Generate a unique referral code for the current user."""
    existing = db.query(ReferralCode).filter_by(user_id=user.id).first()
    if existing:
        return existing
    code = ''.join(random.choices(string.ascii_uppercase + string.digits, k=8))
    referral = ReferralCode(user_id=user.id, code=code, rewards={"leads": 50, "credits": 100})
    db.add(referral)
    db.commit()
    db.refresh(referral)
    return referral

@router.post("/apply", response_model=ApplyReferralResponse, summary="Apply referral code", description="Apply a referral code as a new user to receive rewards.")
def apply_referral_code(req: ApplyReferralRequest, db: Session = Depends(get_db), user: User = Depends(get_current_user)):
    """Apply a referral code as a new user to receive rewards."""
    referral = db.query(ReferralCode).filter_by(code=req.code).first()
    if not referral:
        return ApplyReferralResponse(success=False, message="Invalid referral code", rewards=None)
    if referral.used_by:
        return ApplyReferralResponse(success=False, message="Referral code already used", rewards=None)
    if referral.user_id == user.id:
        return ApplyReferralResponse(success=False, message="Cannot use your own referral code", rewards=None)
    referral.used_by = user.id
    referral.used_at = datetime.utcnow()
    # Example: Give rewards to both users (extend as needed)
    # TODO: Implement actual reward logic (e.g., add credits/leads)
    db.commit()
    return ApplyReferralResponse(success=True, message="Referral code applied! Rewards granted.", rewards=referral.rewards)

@router.get("/status", response_model=List[ReferralOut], summary="Get referral codes/status", description="Get all referral codes generated by the current user.")
def get_referral_status(db: Session = Depends(get_db), user: User = Depends(get_current_user)):
    """Get all referral codes generated by the current user."""
    codes = db.query(ReferralCode).filter_by(user_id=user.id).all()
    return codes 